name: Build and deploy ASP.Net Core app to Azure Web App - bloodbank-management-system
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    
    permissions:
      contents: read #This is required for actions/checkout
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      # Add this diagnostic step to find project files
      - name: Explore repository structure
        shell: pwsh
        run: |
          Get-ChildItem -Path . -Force
          Write-Host "---------- Solution Files ----------"
          Get-ChildItem -Path . -Filter *.sln -Recurse | ForEach-Object { Write-Host $_.FullName }
          Write-Host "---------- Project Files ----------"
          Get-ChildItem -Path . -Filter *.csproj -Recurse | ForEach-Object { Write-Host $_.FullName }
      
      - name: Restore dependencies
        run: dotnet restore BloodBankManagementSystem.sln
        
      - name: Build with dotnet
        run: dotnet build BloodBankManagementSystem.sln --configuration Release --no-restore
        
      - name: dotnet publish
        run: dotnet publish BloodBankManagementSystem.sln -c Release -o "${{env.DOTNET_ROOT}}/myapp" --no-build
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
          
  deploy:
    # The deployment section can remain unchanged
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_23761EAFC02F46ADB482048B37E06773 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CE0939BF62E84E1EA4B6D07A155F7CB6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E3EC6C6D50B949748E1EF7D15D2CF8C1 }}
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bloodbank-management-system'
          slot-name: 'Production'
          package: .
